"""Regenerate tests/fixtures/images.ts. Needs Pillow; the JPEG->BMP case also needs macOS `sips`.

Every fixture is a small synthetic image, so the expected pixels are known exactly and nothing
personal ever goes in the repo.
"""
import base64, io, json, os, subprocess, tempfile
from PIL import Image

W, H = 7, 5  # odd sizes on purpose: catches stride and padding bugs

def rgba_pattern():
    px = []
    for y in range(H):
        for x in range(W):
            px.append(((x * 37) % 256, (y * 61) % 256, ((x + y) * 23) % 256, 255 if (x + y) % 4 else 0))
    return px

def encode(img, **kw):
    buf = io.BytesIO(); img.save(buf, format=kw.pop('fmt', 'PNG'), **kw); return base64.b64encode(buf.getvalue()).decode()

fixtures = {}
base = Image.new('RGBA', (W, H)); base.putdata(rgba_pattern())
expected_rgba = [c for p in rgba_pattern() for c in p]

# Pillow picks filters adaptively and compresses for real: the realistic case.
fixtures['rgba8'] = dict(png=encode(base, optimize=True), width=W, height=H, rgba=expected_rgba)
rgb = base.convert('RGB')
fixtures['rgb8'] = dict(png=encode(rgb), width=W, height=H, rgba=[c for p in rgb.getdata() for c in (*p, 255)])
gray = base.convert('L')
fixtures['gray8'] = dict(png=encode(gray), width=W, height=H, rgba=[c for v in gray.getdata() for c in (v, v, v, 255)])
la = base.convert('LA')
fixtures['grayalpha8'] = dict(png=encode(la), width=W, height=H, rgba=[c for v, a in la.getdata() for c in (v, v, v, a)])
# 16-bit grayscale: we keep the high byte
g16 = Image.new('I;16', (W, H)); g16.putdata([((x * 9000 + y * 3000) % 65536) for y in range(H) for x in range(W)])
fixtures['gray16'] = dict(png=encode(g16), width=W, height=H,
                          rgba=[c for v in g16.getdata() for c in (v >> 8, v >> 8, v >> 8, 255)])
# palette with transparency, and a 1-bit palette (typical of tiny pixel-art PNGs)
pal = base.convert('RGBA').quantize(colors=6)
pal_rgba = pal.convert('RGBA')
fixtures['palette'] = dict(png=encode(pal), width=W, height=H, rgba=[c for p in pal_rgba.getdata() for c in p])
bw = Image.new('1', (W, H)); bw.putdata([255 if (x * y) % 3 else 0 for y in range(H) for x in range(W)])
fixtures['bilevel'] = dict(png=encode(bw), width=W, height=H,
                           rgba=[c for v in bw.convert('L').getdata() for c in (v, v, v, 255)])
# interlaced: must be refused so the loader can fall back to the OS tool
def force_interlaced(png_b64):
    # Pillow can't write Adam7 PNGs (it ignores interlace=1), so flip the IHDR flag and fix its CRC.
    import zlib as _z
    raw = bytearray(base64.b64decode(png_b64))
    raw[8 + 8 + 12] = 1
    crc = _z.crc32(bytes(raw[12:12 + 4 + 13])) & 0xffffffff
    raw[8 + 8 + 13:8 + 8 + 17] = crc.to_bytes(4, 'big')
    return base64.b64encode(bytes(raw)).decode()
fixtures['interlaced'] = dict(png=force_interlaced(encode(rgb)), width=W, height=H, rgba=[])

# A JPEG, converted to BMP by macOS sips exactly the way the loader does it.
if subprocess.run(['which', 'sips'], capture_output=True).returncode == 0:
    with tempfile.TemporaryDirectory() as d:
        big = Image.new('RGB', (64, 40), (200, 60, 20))
        for x in range(64):
            for y in range(40):
                if x > 32: big.putpixel((x, y), (20, 90, 200))
        jpg = os.path.join(d, 'in.jpg'); big.save(jpg, quality=95)
        bmp = os.path.join(d, 'out.bmp')
        subprocess.run(['sips', '-s', 'format', 'bmp', '--resampleHeightWidthMax', '32', jpg, '--out', bmp],
                       capture_output=True, check=True)
        data = open(bmp, 'rb').read()
        decoded = Image.open(bmp).convert('RGBA')
        fixtures['sips_bmp'] = dict(bmp=base64.b64encode(data).decode(), width=decoded.width, height=decoded.height,
                                    rgba=[c for p in decoded.getdata() for c in p])

import zlib
text = (b'pixelband ' * 40) + bytes(range(256)) + b'abcabcabcabcabcabc' * 30
def z(data, level=9, strategy=zlib.Z_DEFAULT_STRATEGY):
    c = zlib.compressobj(level, zlib.DEFLATED, 15, 9, strategy); return c.compress(data) + c.flush()
zcases = {
    'stored': dict(z=base64.b64encode(z(text, 0)).decode(), raw=base64.b64encode(text).decode()),
    'fixed': dict(z=base64.b64encode(z(text, 9, zlib.Z_FIXED)).decode(), raw=base64.b64encode(text).decode()),
    'dynamic': dict(z=base64.b64encode(z(text, 9)).decode(), raw=base64.b64encode(text).decode()),
    'empty': dict(z=base64.b64encode(z(b'')).decode(), raw=''),
}
out = os.path.join(os.path.dirname(__file__), 'images.ts')
with open(out, 'w') as f:
    f.write('// Generated by make_fixtures.py. Do not edit by hand.\n')
    f.write('export const IMAGES: Record<string, { png?: string; bmp?: string; width: number; height: number; rgba: number[] }> = ')
    f.write(json.dumps(fixtures, indent=1))
    f.write('\n')
    f.write('export const ZLIB: Record<string, { z: string; raw: string }> = ' + json.dumps(zcases, indent=1) + '\n')
print('wrote', out, 'with', ', '.join(fixtures))
