"""
Builds tests/fixtures/gifs.ts: GIFs made with Pillow, and the frames Pillow decodes from them, so
hooks/gif.ts is checked pixel for pixel against an independent decoder.

    python tests/fixtures/make_gif_fixtures.py
"""
import base64
import io
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageSequence


def frames_of(data):
    im = Image.open(io.BytesIO(data))
    out = []
    for f in ImageSequence.Iterator(im):
        out.append((f.convert('RGBA').tobytes(), f.info.get('duration', 0)))
    return im.size, out


def make(name, frames, **save):
    buf = io.BytesIO()
    frames[0].save(buf, format='GIF', save_all=len(frames) > 1, append_images=frames[1:], **save)
    data = buf.getvalue()
    size, decoded = frames_of(data)
    return name, {
        'gif': base64.b64encode(data).decode(),
        'width': size[0], 'height': size[1],
        'frames': [base64.b64encode(px).decode() for px, _ in decoded],
        'delays': [d for _, d in decoded],
    }


def ball(i, n=6, w=24, h=16, bg=(20, 30, 60)):
    im = Image.new('RGB', (w, h), bg)
    d = ImageDraw.Draw(im)
    x = 2 + i * (w - 8) // (n - 1)
    d.ellipse((x, 5, x + 5, 10), fill=(250, 200, 40))
    d.line((0, h - 2, w, h - 2), fill=(40, 200, 90))
    return im


fixtures = dict([
    make('still', [ball(0)]),
    make('bounce', [ball(i) for i in range(6)], duration=[80, 80, 120, 120, 0, 50], loop=0),
    make('interlaced', [ball(2, w=40, h=33)], interlace=True),
    make('flat', [Image.new('RGB', (64, 48), (200, 10, 10))]),  # one colour: long LZW runs, the KwKwK case
])

# transparency, with 'restore to background' disposal: the sprite must not leave a trail
sprites = []
for i in range(4):
    im = Image.new('RGBA', (20, 12), (0, 0, 0, 0))
    ImageDraw.Draw(im).rectangle((i * 4, 3, i * 4 + 5, 8), fill=(255, 80, 160, 255))
    sprites.append(im)
fixtures.update(dict([make('sprite_disposal2', sprites, disposal=2, duration=100, loop=0)]))

# 'restore to previous' disposal, and a frame with its own palette
base = Image.new('RGB', (16, 16), (10, 10, 10))
f2 = base.copy(); ImageDraw.Draw(f2).rectangle((4, 4, 11, 11), fill=(0, 255, 255))
f3 = base.copy(); ImageDraw.Draw(f3).rectangle((0, 0, 3, 3), fill=(255, 255, 0))
fixtures.update(dict([make('disposal3', [base, f2, f3], disposal=[1, 3, 1], duration=100, loop=0)]))

# a photo-like gradient: many colours, full 8-bit LZW codes up to 12 bits wide
grad = Image.new('RGB', (96, 64))
grad.putdata([(x * 255 // 95, y * 255 // 63, (x * y) % 256) for y in range(64) for x in range(96)])
fixtures.update(dict([make('gradient', [grad.quantize(256).convert('RGB'), grad.rotate(180).quantize(200).convert('RGB')], duration=40, loop=0)]))

out = Path(__file__).parent / 'gifs.ts'
out.write_text('/** Generated by make_gif_fixtures.py: GIFs and the frames Pillow decodes from them. */\n'
               f'export const GIFS: Record<string, {{ gif: string; width: number; height: number; frames: string[]; delays: number[] }}> = {json.dumps(fixtures, indent=1)}\n')
print(out, {k: (v['width'], v['height'], len(v['frames']), v['delays']) for k, v in fixtures.items()})
