"""
Builds hooks/creation-data.ts, the painting behind the `creation` scene.

Source: Michelangelo, The Creation of Adam (c. 1511), public domain.
https://commons.wikimedia.org/wiki/File:Michelangelo_-_Creation_of_Adam_(cropped).jpg

    python tools/make_creation.py path/to/Michelangelo_-_Creation_of_Adam_(cropped).jpg

Only the strip with the two arms is kept, shrunk and cut to 256 colours, so the plugin ships a
small table of palette indices rather than the photo.
"""
import base64
import sys
from pathlib import Path

from PIL import Image

# The strip we keep, as fractions of the whole painting, and where the fingertips almost touch.
REGION = (0.10, 0.20, 0.66, 0.72)
GAP = (0.380, 0.452)
FULL_WIDTH = 750  # the painting's width at the scale we keep it

src = Image.open(sys.argv[1]).convert('RGB')
scale = FULL_WIDTH / src.width
full = src.resize((FULL_WIDTH, round(src.height * scale)), Image.LANCZOS)
W, H = full.size
box = (round(REGION[0] * W), round(REGION[1] * H), round(REGION[2] * W), round(REGION[3] * H))
strip = full.crop(box)
q = strip.quantize(256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
palette = bytes(q.getpalette()[: 256 * 3])
indices = q.tobytes()

gap_x = GAP[0] * W - box[0]
gap_y = GAP[1] * H - box[1]
out = Path(__file__).resolve().parent.parent / 'hooks' / 'creation-data.ts'
out.write_text(f"""/**
 * The painting behind the `creation` scene: Michelangelo, The Creation of Adam (c. 1511), public
 * domain, via Wikimedia Commons. The strip with the two arms, {strip.width}x{strip.height}, cut to
 * 256 colours. Generated by tools/make_creation.py; don't edit by hand.
 */
export const CREATION = {{
  width: {strip.width},
  height: {strip.height},
  /** The whole painting's width, in this strip's pixels. */
  fullWidth: {W},
  /** Where the fingertips almost touch, in this strip's pixels. */
  gap: {{ x: {gap_x:.1f}, y: {gap_y:.1f} }},
  palette: '{base64.b64encode(palette).decode()}',
  indices: '{base64.b64encode(indices).decode()}',
}}
""")
print(out, strip.size, len(indices), 'bytes of indices')
